openapi: 3.1.0
info:
  version: '2.0'
  title: Хялбар бүртгэлийн API холболт
  summary: ''
  description: "### Танилцуулга\r\n>Иргэний хувийн хэрэглээнд худалдан авсан бараа бүтээгдэхүүний худалдан авалт болон үйлчилгээний төлбөр төлсөн тухай бүр үйлдсэн төлбөрийн баримтын мэдээллийг автоматаар ибаримт системд бүртгэх үйлчилгээг хялбар бүртгэл гэнэ.\r\n\r\n![image (2).png](<../assets/images/Image (1).jpg>)\r\n\r\n\r\n### Өөрчлөлтийн түүх\r\n\r\n| № | Хувилбар | Огноо | Тайлбар | Хариуцагч |\r\n| -------- | ------- | ------- | ------- | ------- |\r\n| 1  | 1.0.0 | 08/09/2024 | Гарын авлага боловсруулав | Б.Мөнгөнчимэг   |\r\n"
paths:
  '/api/easy-register/api/info/consumer/{identity}':
    get:
      summary: Иргэний мэдээлэл регистр /иргэний бүртгэл-civilId/-ийн дугаараар лавлах
      description: '>Худалдан авагч иргэний мэдээлийг дараах зааврын дагуу лавлана.'
      operationId: get-api-easy-register-api-info-consumer-regNo
      parameters:
        - name: identity
          in: path
          description: Иргэний регистрийн дугаар болон иргэний бүртгэлийн дугаар/civilId/-ын нэг нь байна.
          required: true
          schema:
            type: string
            examples:
              - АА01234567
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  regNo:
                    type: string
                    description: Иргэний регистрийн дугаар
                  loginName:
                    type: string
                    description: Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн код
                  givenName:
                    type: string
                    description: Хэрэглэгчийн нэр
                  familyName:
                    type: string
                    description: Хэрэглэгчийн овог
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
              examples:
                Example 1:
                  value:
                    regNo: ТЕ8****818
                    loginName: '11223344'
                    givenName: Очир
                    familyName: Даваа
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Сервисийн хариу мессеж
                  code:
                    type: string
                    description: Сервисийн хариу код
                  status:
                    type: string
                    description: Сервисийн хариу статус
                required:
                  - msg
                  - code
                  - status
              examples:
                Регистрийн дугаар бүртгэлгүй үед:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: '409'
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn'
          description: Хөгжүүлэлтийн орчин
  /api/easy-register/rest/v1/getProfile:
    post:
      summary: Иргэний мэдээллийг утасны дугаараар болон хэрэглэгчийн дугаараар лавлах
      description: ">Худалдан авагч иргэний мэдээллийг утасны дугаараар болон хэрэглэгчийн дугаараар лавлах\r\n"
      operationId: post-api-easy-register-rest-v1-getProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNum:
                  type: string
                  description: Иргэний утасны дугаар /Хэрэглэгчийн дугаар талбарт өгөдөл оруулсан бол заавал биш/
                  examples:
                    - '99999999'
                customerNo:
                  type: string
                  description: Хэрэглэгчийн дугаарр./Иргэний утасны дугаар талбарт өгөдөл оруулсан бол заавал биш/
                  examples:
                    - '10038071'
              required:
                - phoneNum
                - customerNo
            examples:
              Утасны дугаараар лавлах:
                value:
                  phoneNum: 993***99
              Хэрэглэгчийн дугаараар лавлах:
                value:
                  customerNo: АА12345678
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Сервисийн хариу
                  code:
                    type: string
                    description: Сервисийн хариу
                  status:
                    type: number
                    description: Сервисийн хариу
                  loginName:
                    type: string
                    description: "Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн\r\nкод."
                  email:
                    type: string
                    description: Хэрэглэгчийн цахим шуудан хаяг
                required:
                  - msg
                  - code
                  - status
                  - loginName
                  - email
              examples:
                Амжилттай:
                  value:
                    msg: Амжилттай.
                    code: success
                    status: 200
                    loginName: 11***475
                    email: munguu****@yahoo.com
                Хэрэглэгч олдоогүй:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: 409
                    loginName: ''
                    email: ''
                Давхар бүртгэлтэй хэрэглэгч:
                  value:
                    msg: Хэрэглэгчийн бүртгэл давхардсан байна.
                    code: userDuplicate
                    status: 409
                    loginName: ''
                    email: ''
                Насанд хүрээгүй хэрэглэгч:
                  value:
                    msg: Хэрэглэгч 14 наснаас доош байна.
                    code: userChild
                    status: 409
                    loginName: ''
                    email: ''
                Цахим шуудан хаяг бүртгэлгүй:
                  value:
                    msg: Имэйл олдсонгүй
                    code: emailNotFound
                    status: 409
                    loginName: ''
                    email: ''
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Сервисийн хариу
                  code:
                    type: string
                    description: Сервисийн хариу
                  status:
                    type: number
                    description: Сервисийн хариу
                  loginName:
                    type: string
                    description: "Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн\r\nкод"
                  email:
                    type: string
                    description: Хэрэглэгчийн цахим шуудан хаяг
                required:
                  - msg
                  - code
                  - status
                  - loginName
                  - email
              examples:
                Талбар хоосон:
                  value:
                    msg: Талбар хоосон байна.
                    code: emptyField
                    status: 400
                    loginName: ''
                    email: ''
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn/'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn/'
          description: Хөгжүүлэлтийн орчин
  /api/easy-register/rest/v1/approveQr:
    post:
      summary: Төлбөрийн баримт баталгаажуулах
      description: '>Энэхүү сервис нь тухайн иргэнийн ибаримтанд Баталгаажсан төлөвтэйгээр шууд бүртгэгдэх болно.'
      operationId: post-api-easy-register-rest-v1-approveQr
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customerNo:
                  type: string
                  description: E-barimt-н нэвтрэх хэрэглэгчийн код. (8-9 оронтой тоо байх)
                  examples:
                    - '10038071'
                qrData:
                  type: string
                  description: Төлбөрийн баримтын QR
              required:
                - customerNo
                - qrData
            examples:
              Төлбөрийн баримтын баталгаажуулах:
                value:
                  customerNo: АА12345678
                  qrData: 138431709438294994***********42989187861711452070 67124287171260511392558330701380
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Сервисийн хариу
                  code:
                    type: string
                    description: Сервисийн хариу
                  status:
                    type: number
                    description: Сервисийн хариу
                required:
                  - msg
                  - code
                  - status
              examples:
                Амжилттай:
                  value:
                    msg: Амжилттай.
                    code: SUCCESS
                    status: 200
                Хэрэглэгч олдсонгүй:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: 409
                QR алдаатай:
                  value:
                    msg: qrData мэдээлэл алдаатай байна.
                    code: inValidQr
                    status: 500
                Мэдээлэл алдаатай:
                  value:
                    msg: Мэдээлэл алдаатай байна.
                    code: invalidData
                    status: 500
                Алдаатай:
                  value:
                    msg: Алдаа.
                    code: error
                    status: 500
                Баримтын төрөл буруу:
                  value:
                    msg: Байгууллага хооронд хийгдсэн гүйлгээ баталгаажуулах боломжгүй.
                    code: b2bNotAccepted
                    status: 500
                Сугалааны дугаар байхгүй:
                  value:
                    msg: Сугалаагүй баримт байна.
                    code: noLotteryQr
                    status: 409
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Сервисийн хариу
                  code:
                    type: string
                    description: Сервисийн хариу
                  status:
                    type: number
                    description: Сервисийн хариу
                required:
                  - msg
                  - code
                  - status
              examples:
                Талбар хоосон:
                  value:
                    msg: Талбар хоосон байна.
                    code: emptyField
                    status: 400
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn/'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn/'
          description: Хөгжүүлэлтийн орчин
  '/api/easy-register/api/info/foreigner/{identity}':
    get:
      summary: Гадаад жуулчны мэдээллийг гадаад паспорт эсвэл F регистрийн дугаараар лавлах
      description: '> Энэхүү сервис нь Монголын улсад аялаж байгаа гадаадын иргэний мэдээллийг f регистр болон гадаад паспортын дугаараар лавлахад ашиглагдана.'
      operationId: get-api-easy-register-api-info-foreigner
      parameters:
        - name: identity
          in: path
          description: Гадаад пасспортын дугаар эсвэл Хил хамгаалах ерөнхий газраас олгосон F регистрийн дугаар /аль нэгийг нь оруулж лавлана.
          required: true
          schema:
            type: string
            examples:
              - M709R8406
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  regNo:
                    type: string
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    description: "Ebarimt-н нэвтрэх нэр буюу 8 оронтой хэрэглэгчийн код.\r\n"
                  givenName:
                    type: string
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    description: Гадаад паспортын дугаар.
                  fNumber:
                    type: string
                    description: F регистрийн дугаар.
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - fNumber
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    fNumber: '******'
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn/'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn'
          description: Хөгжүүлэлтийн орчин
  '/api/easy-register/api/info/foreigner/customerNo/{loginName}':
    get:
      summary: Гадаад жуулчны мэдээллийг E-barimt-н нэвтрэх нэрээр лавлах
      description: '> Энэхүү сервис нь Монгол улсад аялаж байгаа гадаадын иргэний мэдээллийг ИБАРИМТ-ын нэвтрэх нэрээр лавлахад ашиглагдана.'
      operationId: get-api-easy-register-api-info-foreigner-customerNo
      parameters:
        - name: loginName
          in: path
          description: E-barimt-н нэвтрэх хэрэглэгчийн код. (8-9 оронтой тоо байх)
          required: true
          schema:
            type: string
            examples:
              - '10038071'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  regNo:
                    type: string
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    description: Ebarimt-н нэвтрэх хэрэглэгчийн код.
                  givenName:
                    type: string
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    description: Гадаад паспортын дугаар.
                  fNumber:
                    type: string
                    description: F регистрийн дугаар.
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - fNumber
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    fNumber: '*******'
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn'
          description: Хөгжүүлэлтийн орчин
  '/api/easy-register/api/info/foreigner/{passportNo}':
    post:
      summary: Гадаад жуулчны мэдээллийг E-barimt-н системд бүртгэх
      description: '>Гадаад жуулчны мэдээллийг Гадаад паспортын дугаар болон цахим шуудан хаягаар EBARIMT-н системд бүртгэх'
      operationId: post-api-easy-register-api-info-foreigner-passportNo
      parameters:
        - name: passportNo
          in: path
          description: Гадаад пасспортын дугаар
          required: true
          schema:
            type: string
            examples:
              - EK2658447
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Гадаад иргэний цахим шуудан хаяг
              required:
                - email
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  regNo:
                    type: string
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    description: Ebarimt-н нэвтрэх хэрэглэгчийн код.
                  givenName:
                    type: string
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    description: Гадаад паспортын дугаар.
                  message:
                    type: string
                    description: Сервисийн хариу
                  fNumber:
                    type: string
                    description: F регистрийн дугаар.
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - message
                  - fNumber
                x-examples:
                  Example 1:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    message: You are already registered. Please check your oc********@itc.gov.mn
                    fNumber: ''
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    message: You are already registered. Please check your oc********@itc.gov.mn
                    fNumber: ''
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn'
          description: Хөгжүүлэлтийн орчин
  /api/easy-register/rest/v1/setReturnReceipt:
    post:
      summary: Хялбар бүртгэлээр бүртгэгдсэн төлбөрийн баримтын буцаалтыг баталгаажуулах сервис
      description: '>Энэхүү сервис нь зөвхөн ПосАПИ системээс хэвлэсэн сугалаатай баримтын буцаалтыг баталгаажуулах зориулалттай ба буцаах үйлдэл хийж буй баримтыг иргэн талаас буцаасны дараа баталгаажуулах боломжтой болохыг анхаарна уу. Мөн “Багц баримт”-ын систем ашиглан илгээсэн толгой баримтыг буцаахад дэд баримт дагаж идэвхгүй болох ба дэд баримтыг дангаар нь буцаах боломжгүй. '
      operationId: post-api-easy-register-rest-v1-setReturnReceipt
      parameters:
        - name: X-API-KEY
          in: header
          description: posapi@itc.gov.mn рүү хүсэлт илгээж авна
          required: true
          schema:
            type: string
            examples:
              - eaab09fdb83c4affc210b8fb96f9977db7978e8a
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                posRno:
                  type: string
                  description: Төлбөрийн баримтын ДДТД /Сугалааны дугаар байхгүй бол ДДТД/
                  examples:
                    - 0000061********230518000112012889
                lotteryNumber:
                  type: string
                  description: Төлбөрийн баримтын сугалааны дугаар /ДДТД байхгүй бол сугалааны дугаар/
                  examples:
                    - AA11111111
              x-examples:
                Example 1:
                  posRno: 0000061********230518000112012889
            examples:
              ДДТД дугаараар буцаалт хийх:
                value:
                  posRno: 0000061********230518000112012889
              Сугалааны дугаараар буцаалт хийх:
                value:
                  lotteryNumber: AA11111111
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    examples:
                      - Амжилттай
                  status:
                    type: number
                    examples:
                      - 200
                  code:
                    type: 'null'
                  data:
                    type: 'null'
                x-examples:
                  Example 1:
                    msg: ' Амжилттай буцаасан.'
                    status: 200
                    code: null
                    data: null
              examples:
                Амжилтттай:
                  value:
                    msg: Амжилттай
                    status: 200
                    code: null
                    data: null
                ДДТД эсвэл сугалааны дугаар хоосон байна:
                  value:
                    msg: string
                    status: 0
                    code: null
                    data: null
                Баримтын мэдээлэл олдсонгүй:
                  value:
                    msg: Баримтын мэдээлэл олдсонгүй
                    status: 500
                    code: null
                    data: null
                Токены мэдээлэл алдаатай байна:
                  value:
                    msg: Токены мэдээлэл алдаатай байна
                    status: 500
                    code: null
                    data: null
                Өөр байгууллагын борлуулалтын баримт тул устгаж болохгүй:
                  value:
                    msg: Өөр байгууллагын борлуулалтын баримт тул устгаж болохгүй
                    status: 500
                    code: null
                    data: null
                Хэрэглэгч буцаах үйлдэл хийгээгүй баримт байна:
                  value:
                    msg: Хэрэглэгч буцаах үйлдэл хийгээгүй баримт байна
                    status: 500
                    code: null
                    data: null
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
      security:
        - auth.yaml: []
      servers:
        - url: 'https://service.itc.gov.mn/'
          description: Бодит орчин
        - url: 'https://st-service.itc.gov.mn/'
          description: Туршилтын орчин
components:
  securitySchemes:
    auth.yaml:
      type: http
      scheme: bearer
x-internal: false
