openapi: 3.1.0
x-stoplight:
  id: c1tfgzwv4fe23
info:
  version: 1.0.0
  title: Цахим төлбөрийн баримт API холболт
  description: |-
    ## Танилцуулга
    > Монгол Улсад импортоор оруулсан, эсхүл Монгол Улсаас экспортод гаргасан болон Монгол Улсын нутаг дэвсгэрт бараа борлуулсан, ажил гүйцэтгэсэн, үйлчилгээ үзүүлсэн
    > этгээдийн бараа, ажил, үйлчилгээний цахим баримтын мэдээллийг цуглуулах, боловсруулах, тайлагнах үйл ажиллагааг зохион байгуулах систем юм. Мөн нэмэгдсэн өртгийн албан
    > татварын урамшуулал, буцаан олголтыг бүртгэх, олгох ажиллагаа энэхүү системийг ашиглан гүйцэтгэдэг.

    ### Нэвтрэлтийн системийн сервисийн хаяг
    | Сервисийн нэр | Хөгжүүлэлтийн орчинд | Бодит орчинд |
    | -------- | ------- | ------- |
    | TOKEN | https://st.auth.itc.gov.mn/auth/realms/Staging | https://auth.itc.gov.mn/auth/realms/ITC |



    ### Өөрчлөлтийн түүх

    | № | Хувилбар | Огноо | Тайлбар | Хариуцагч |
    | -------- | ------- | ------- | ------- | ------- |
    | 1  | 1.0.0 | 05/22/2023 | Гарын авлага боловсруулав | Б.Мөнгөнчимэг   |
paths:
  /api/tpi/receipt/getSalesTotalData:
    post:
      summary: Борлуулалтын задаргааны мэдээлэл татах сервис
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - status
                  - code
                  - data
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: 8tvdf6finsmcd
                    description: Сервисийн хариу
                  status:
                    type: number
                    x-stoplight:
                      id: qy79i175q6mic
                    default: 200
                  code:
                    type: string
                    x-stoplight:
                      id: ozgflr8huaw6n
                  data:
                    type: object
                    x-stoplight:
                      id: 0nhpr88qwx63l
                    required:
                      - list
                    properties:
                      list:
                        type:
                          - array
                        x-stoplight:
                          id: 3k23s91dpgsow
                        items:
                          x-stoplight:
                            id: kbhvdo1dtvnao
                          type: object
                          required:
                            - posSid
                            - posRno
                            - posRdate
                            - posRamt
                            - citytax
                            - posVamt
                            - netAmt
                            - fromType
                            - csmrRegNo
                            - csmrName
                            - posNo
                            - operatorName
                            - districtCode
                          properties:
                            posSid:
                              type: string
                              x-stoplight:
                                id: bpe75y104c86e
                              description: 'Посын системийн дугаар '
                            posRno:
                              type: string
                              x-stoplight:
                                id: a5ehnr1vkvj1d
                              description: Төлбөрийн баримтын ДДТД
                            posRdate:
                              type: string
                              x-stoplight:
                                id: 0e6hxw7k85dc3
                              description: Төлбөрийн баримтын огноо
                            posRamt:
                              type: number
                              x-stoplight:
                                id: iydxn7sgfcaui
                              description: Төлбөрийн баримтын нийт дүн
                            citytax:
                              type: number
                              x-stoplight:
                                id: 5b7zjw13rb3v7
                              description: Нийслэл хотын албан татвар
                            posVamt:
                              type: number
                              x-stoplight:
                                id: 2nv7ko6rbh648
                              description: Нэмэгдсэн өртгийн албан татвар
                            netAmt:
                              type: number
                              x-stoplight:
                                id: s5zonpv66lt5a
                              description: Төлбөрийн баримтын цэвэр дүн
                            fromType:
                              type: string
                              x-stoplight:
                                id: tv9hcfdv8lokw
                              description: 'Хаанаас үүсгэсэн /POS, ebarimt/'
                            csmrRegNo:
                              type: string
                              x-stoplight:
                                id: 71j8trgpryybl
                              description: Худалдан авагчийн регистр
                            csmrName:
                              type: string
                              x-stoplight:
                                id: 0mjp74904q8mg
                              description: Худалдан авагчийн нэр
                            posNo:
                              type: string
                              x-stoplight:
                                id: dm6odq1th3tir
                              description: Посын дугаар
                            operatorName:
                              type: string
                              x-stoplight:
                                id: w1lbw7gm7rgcq
                              description: Хэрэглэгчийн систем нийлүүлэгчийн нэр
                            districtCode:
                              type: string
                              x-stoplight:
                                id: edtk0j8qxyhvb
                              description: Төлбөрийн баримтын байршлын нэр
                            prParentRno:
                              type: string
                              x-stoplight:
                                id: pcvl1hohirxg4
                              description: Төлбөрийн баримтын толгой нэхэмжлэхийн дугаар
                      pageModel:
                        type: object
                        x-stoplight:
                          id: qzu3nrpwu31in
                        required:
                          - totalElements
                        properties:
                          totalElements:
                            type: number
                            x-stoplight:
                              id: krtrja0i2rnvh
                            description: Нийт баримтын тоо
                      '':
                        type: string
                        x-stoplight:
                          id: e7xo4qugrpzpe
              examples:
                Өгөгдөл татах үйлдэл амжилттай:
                  value:
                    msg: Амжилттай
                    status: 200
                    code: null
                    data:
                      content:
                        - posSid: 32***73
                          posRno: 0000054355*******0907000001014141
                          posRdate: '2023-09-07 22:50:46'
                          posRamt: 3000
                          citytax: 0
                          posVamt: 272.727273
                          netAmt: 2727.272727
                          fromType: ebarimt
                          csmrRegNo: 20***25
                          csmrName: МОНГ**** *** **К
                          posNo: '001'
                          operatorName: TEST OPERATOR 1
                          districtCode: Архангай
                      pageModel:
                        totalElements: 10
                Мэдээлэл татах эрхгүй токен ашигласан үед:
                  value:
                    msg: Ерөнхий нягтлан биш байна.
                    Status: 500
                    code: null
                    data: null
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - timestamp
                  - status
                  - error
                  - message
                  - path
                properties:
                  timestamp:
                    type: string
                    x-stoplight:
                      id: keruuapapkb6h
                  status:
                    type: number
                    x-stoplight:
                      id: regolmseltd16
                  error:
                    type: string
                    x-stoplight:
                      id: inhrvtmo7ay9y
                  message:
                    type: string
                    x-stoplight:
                      id: zhx5xzp6swb6k
                  path:
                    type: string
                    x-stoplight:
                      id: ka7dj3wkngqkx
              examples:
                Request body алдаатай:
                  value:
                    timestamp: '2024-06-22T09:36:48.624+00:00'
                    status: 400
                    error: Bad Request
                    message: Bad Request
                    path: /api/tpi/receipt/getSalesTotalData
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                required:
                  - timestamp
                  - path
                  - status
                  - error
                  - requestId
                properties:
                  timestamp:
                    type: string
                    x-stoplight:
                      id: r6xtrrnqe8i7f
                  path:
                    type: string
                    x-stoplight:
                      id: 1jy54yhd20xus
                  status:
                    type: number
                    x-stoplight:
                      id: bou79jzgj7bos
                  error:
                    type: string
                    x-stoplight:
                      id: xxwam2hvcxfr9
                  requestId:
                    type: string
                    x-stoplight:
                      id: 1yfclsiac8ssj
              examples:
                Key буруу:
                  value:
                    timestamp: '2024-06-22T09:15:52.440+00:00  '
                    path: /api/tpi/receipt/getSalesTotalData
                    status: 401
                    error: Unauthorized
                    requestId: b3382530-32
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    x-stoplight:
                      id: e8zuz2716s3p6
                  status:
                    type: number
                    x-stoplight:
                      id: coxfw1i282wyn
                  error:
                    type: string
                    x-stoplight:
                      id: qkaqrrmqwp4pp
                  message:
                    type: string
                    x-stoplight:
                      id: m3rvsbql8x2kb
                  path:
                    type: string
                    x-stoplight:
                      id: 51ofu496hz9d9
              examples:
                Алдаатай үед:
                  value:
                    timestamp: '2024-06-22T09:36:48.624+00:00'
                    status: 500
                    error: internal server error
                    message: internal server error
                    path: /api/tpi/receipt/getSalesTotalData
      operationId: post-api-tpi-receipt-getSalesTotalData
      x-stoplight:
        id: amem8bql9kgmn
      description: "Цахим төлбөрийн баримтын системд их хэмжээний борлуулалтын баримт илгээдэг, том сегментэд харьяалагддаг татвар төлөгч нар борлуулалтын задаргаагаа өөрийн санхүүгийн системээс татах боломжийг бүрдүүлэхэд энэхүү сервис ашиглагдана.\r\n[Нэгдсэн нэвтрэлтийн token авах бол дарна уу.](reference/auth.yaml/paths/~1protocol~1openid-connect~1token/post)\r\n<!-- theme: danger -->\r\n> Анхаарах асуудал: Хэрэглэгч сервисийг зөвхөн шөнийн цагаар буюу шөнийн 1:00 цагаас өглөөний 7:00 цагийн хооронд дуудан ашиглах боломжтой."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - year
                - month
                - status
                - startCount
                - endCount
              properties:
                year:
                  type: string
                  x-stoplight:
                    id: yjvond58nmsr7
                  description: Задаргаа авч буй баримтын он
                month:
                  type: string
                  x-stoplight:
                    id: 8xuj6gfwttsbz
                  description: Задаргаа авч буй баримтын сар
                status:
                  type: number
                  x-stoplight:
                    id: rozdqjxrmtfd1
                  description: Задаргаа авч буй баримтын төрөл
                  default: 0
                  example: '0 - Нийт борлуулалтын баримт, 1 - Бизнес эрхлэгч хооронд үүсгэсэн баримт, 2 - Эцсийн хэрэглээ буюу сугалаатай баримт, 3 - Нэхэмжлэх, 4 - Багцын толгой баримт'
                startCount:
                  type: number
                  x-stoplight:
                    id: 40815w1a3cmif
                  description: Тухайн баримтын эхлэх тоо
                endCount:
                  type: number
                  x-stoplight:
                    id: mxl8rrtjfl678
                  description: Тухайн баримтын дуусах тоо
                day:
                  type: string
                  x-stoplight:
                    id: g6fjuuavl0qrx
                  description: Задаргаа авч буй баримтын өдөр /Заавал биш/
            examples:
              Задаргаа авах JSON:
                value:
                  year: '2024'
                  month: '01'
                  status: 0
                  startCount: 0
                  endCount: 100
                  day: '12'
      x-internal: false
      parameters:
        - schema:
            type: string
            example: 'Туршилтын орчинд ашиглах: 9406e79323ec0fed4e560342bce72221107a808b'
          in: header
          name: X-API-KEY
          description: Татварын ерөнхий газрын-Татвар төлөгчид үйлчлэх газарт албан тоотоор хүсэлт гарган авна.
          required: true
      security:
        - auth.yaml: []
    servers:
      - url: 'https://api.ebarimt.mn/'
        description: Бодит орчин
      - url: 'https://st-api.ebarimt.mn/'
        description: Хөгжүүлэлтийн орчин
    parameters:
      - schema:
          type: string
        in: header
        name: X-API-KEY
        description: Татварын ерөнхий газраас олгоно
        required: true
  /api/tpi/receipt/getSaleListERP:
    post:
      summary: Толгой татвар төлөгч өөрийн охин компанийн худалдан авалт татах сервис
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - status
                  - code
                  - data
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: m2thdfygb48qr
                    description: Сервисийн хариу
                    example: Амжилттай
                  status:
                    type: number
                    x-stoplight:
                      id: mu336zxux6qw9
                    description: Төлөв
                    example: 200
                  code:
                    type: string
                    x-stoplight:
                      id: ituw4fpcdwigj
                    description: Код
                  data:
                    type: array
                    x-stoplight:
                      id: 3xplyy74ubdux
                    items:
                      x-stoplight:
                        id: jgjw63wgvhbz7
                      type: object
                      required:
                        - startDate
                        - endDate
                        - regNo
                        - receiptBuyModelList
                      properties:
                        startDate:
                          type: string
                          x-stoplight:
                            id: 8jfmayv5bmzvw
                          description: Эхлэх огноо
                          example: '2024-01-01 00:00:00'
                        endDate:
                          type: string
                          x-stoplight:
                            id: rehg7dpu8wvxi
                          description: Дуусах огноо
                          example: '2024-04-30 23:59:59'
                        regNo:
                          type: string
                          x-stoplight:
                            id: n5wt7m76aibsw
                          description: Толгой компанийн регистр
                          example: '99119911'
                        receiptBuyModelList:
                          type: array
                          x-stoplight:
                            id: om2rrn9y7s1w4
                          description: Худалдан авалтын баримтын жагсаалт
                          items:
                            x-stoplight:
                              id: y0kmvm3pu14c7
                            type: object
                            required:
                              - prPosRno
                              - name
                              - regNo
                              - buyerRegNo
                              - date
                              - amountVat
                              - amountCitytax
                              - amountTotal
                              - amountNet
                              - fromType
                              - receiptType
                            properties:
                              prPosRno:
                                type: string
                                x-stoplight:
                                  id: fqbo450njf5cy
                                description: Төлбөрийн баримтын ДДТД
                                example: '000005743087000240101000001411087'
                              name:
                                type: string
                                x-stoplight:
                                  id: y9n2ia3ow0mqq
                                description: Борлуулагчийн нэр
                              regNo:
                                type: string
                                x-stoplight:
                                  id: f7zr033ba3exk
                                description: Борлуулагчийн регистр
                                example: ГУР*****МБА
                              buyerRegNo:
                                type: string
                                x-stoplight:
                                  id: 0ivbs9lb3xn3w
                                description: Худалдан авагчийн регистр
                                example: 57***87
                              date:
                                type: string
                                x-stoplight:
                                  id: 7682wuxihrer3
                                description: Баримт хэвлэсэн огноо
                                example: '2024-01-01 03:34:36'
                              amountVat:
                                type: number
                                x-stoplight:
                                  id: kbnup6fmmgrgg
                                description: НӨАТ
                                example: 252.272727
                              amountCitytax:
                                type: number
                                x-stoplight:
                                  id: 80l6wkn89yrat
                                description: НХАТ
                                example: 0
                              amountTotal:
                                type: number
                                x-stoplight:
                                  id: jvt3xhidszct4
                                description: Төлбөрийн баримтын нийт дүн
                                example: 2775
                              amountNet:
                                type: number
                                x-stoplight:
                                  id: 33jk9nrag2wi2
                                description: Төлбөрийн баримтын цэвэр дүн
                                example: 2522.727273
                              fromType:
                                type: string
                                x-stoplight:
                                  id: t830xajy5oder
                                description: 'Хаанаас баримт хэвлэсэн /INVOICE, POS API/'
                                example: INVOICE
                              receiptType:
                                type: string
                                x-stoplight:
                                  id: 29862h1teux6v
                                description: 'Төлбөрийн баримтын төрөл /ТӨЛБӨРИЙН БАРИМТ, НЭХЭМЖЛЭХ/'
                                example: ТӨЛБӨРИЙН БАРИМТ
              examples:
                Өгөгдөл татах үйлдэл амжилтгүй:
                  value:
                    msg: 'Мэдээлэл авах эрхтэй хэрэглэгч биш байна. '
                    status: 500
                    code: null
                    data: null
                Өгөгдөл татах үйлдэл амжилтгүй-1:
                  value:
                    msg: 'Охин  компанийн мэдээлэл алдаатай '
                    status: 500
                    code: null
                    data: null
                Өгөгдөл амжилттай татагдсан:
                  value:
                    msg: Амжилттай
                    status: 200
                    code: null
                    data:
                      - startDate: '2024-01-01 00:00:00'
                        endDate: '2024-04-30 23:59:59'
                        regNo: '99119911'
                        receiptBuyModelList:
                          - prPosRno: '000005743087000240101000001411087'
                            name: string
                            regNo: ГУР*****МБА
                            buyerRegNo: 57***87
                            date: '2024-01-01 03:34:36'
                            amountVat: 252.272727
                            amountCitytax: 0
                            amountTotal: 2775
                            amountNet: 2522.727273
                            fromType: INVOICE
                            receiptType: ТӨЛБӨРИЙН БАРИМТ
        '401':
          description: Unauthorized
      operationId: post-api-tpi-receipt-getSaleListERP
      x-stoplight:
        id: 2mi7tvxyzkxsi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - pin
                - startDate
                - endDate
              properties:
                pin:
                  type: string
                  x-stoplight:
                    id: jtxlmrtlbco7c
                  description: Толгой компанийн регистрийн дугаар
                startDate:
                  type: string
                  x-stoplight:
                    id: ad8wn8g92xws7
                  description: Баримт татах эхлэх огноо
                subPin:
                  type: array
                  x-stoplight:
                    id: 8bmej7mrbah5h
                  description: Охин компанийн регистрийн дугаар. Хэрэв регистр оруулахгүй бол толгой компанийн мэдээлэл татагдах
                  items:
                    x-stoplight:
                      id: azq1nojw8eeij
                    type: string
                endDate:
                  type: string
                  x-stoplight:
                    id: 1p0h0ldclgs1p
                  description: Баримт татах дуусах огноо
            examples:
              Толгой компанийн худалдан авалт татах:
                value:
                  pin: '99119911'
                  startDate: '2024-01-01 00:00:00'
                  subPin: []
                  endDate: '2024-04-30 23:59:59'
              Охин компанийн худалдан авалт татах:
                value:
                  Pin: '99119911'
                  StartDate: '2024-01-01'
                  subPin:
                    - '99119913'
                  EndDate: '2024-04-30'
      parameters:
        - schema:
            type: string
            example: 'Туршилтын орчинд ашиглах: 9406e79323ec0fed4e560342bce72221107a808b'
          in: header
          name: X-API-KEY
          description: Татварын ерөнхий газрын-Татвар төлөгчид үйлчлэх газарт албан тоотоор хүсэлт гарган авна.
          required: true
      description: '> Энэхүү сервис нь толгой татвар төлөгч буюу бусад хуулийн этгээдийн хувьцаа эзэмшигчээр бүртгэлтэй хуулийн этгээд нь өөрийн охин компанийн худалдан авалтын мэдээллийг татахад ашиглагдана. [Нэгдсэн нэвтрэлтийн token авах бол дарна уу.](reference/auth.yaml/paths/~1protocol~1openid-connect~1token/post)'
      security:
        - auth.yaml: []
    servers:
      - url: 'https://api.ebarimt.mn'
        description: Бодит орчин
      - url: 'https://st-api.ebarimt.mn'
        description: Хөгжүүлэлтийн орчин
  /rest/e-inventory-service/api/v1/tpiDeclaration:
    servers:
      - url: 'https://data.ebarimt.mn'
        description: Бодит орчин
      - url: 'https://st-inventory.ebarimt.mn'
        description: Туршилтын орчин
    post:
      summary: Хуулийн этгээдийн гаалийн мэдүүлэг татах сервис
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    content:
                      - dclrNo: 14215******I25514
                        dclrDate: '2020-09-24T09:15:58.000+0000'
                        items:
                          - goodsnm: 'Нүүрс, коксжих, боловсруулаагүй'
                            itemuprc: 0.0493
                            dutyamt: 0
                            exciseamt: 0
                            formamt: 0
                            vatBaseAmt: 0
                            vatamt: 0
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      required:
                        - dclrNo
                        - dclrDate
                        - items
                      properties:
                        dclrNo:
                          type: string
                          example: 14215******I25514
                        dclrDate:
                          type: string
                          example: '2020-09-24T09:15:58.000+0000'
                        items:
                          type: array
                          items:
                            type: object
                            required:
                              - goodsnm
                              - itemuprc
                              - vatBaseAmt
                            properties:
                              goodsnm:
                                type: string
                                example: 'Нүүрс, коксжих, боловсруулаагүй'
                              itemuprc:
                                type: number
                                example: 0.0493
                              dutyamt:
                                type: number
                                example: 0
                              exciseamt:
                                type: number
                                example: 0
                              formamt:
                                type: number
                                example: 0
                              vatBaseAmt:
                                type: number
                                example: 0
                              vatamt:
                                type: number
                                example: 0
              examples:
                Амжилттай:
                  value:
                    content:
                      - dclrNo: 14215******I25514
                        dclrDate: '2020-09-24T09:15:58.000+0000'
                        items:
                          - goodsnm: 'Нүүрс, коксжих, боловсруулаагүй'
                            itemuprc: 0.0493
                            dutyamt: 0
                            exciseamt: 0
                            formamt: 0
                            vatBaseAmt: 0
                            vatamt: 0
      operationId: post-rest-e-inventory-service-api-v1-tpiDeclaration
      x-stoplight:
        id: 6q7guc0bs8yyd
      description: '>Энэхүү сервис нь хуулийн этгээд гаалийн мэдүүлгийг татах зориулалттай.[Нэгдсэн нэвтрэлтийн token авах бол дарна уу.](reference/auth_copy.yaml/paths/~1protocol~1openid-connect~1token/post)'
      security:
        - auth_copy.yaml: []
      parameters:
        - schema:
            type: string
            example: 'Туршилтын орчинд ашиглах: 4816801d5e75e24f2b2dad2820e0c4872bcdbd64'
          in: header
          name: X-API-KEY
          description: Гаалийн ерөнхий газрын Мэдээллийн технологийн газарт албан бичгээр хандаж авна.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  startDate: '2020-03-01'
                  endDate: '2024-03-30'
                  pageNumber: 1
                  pageSize: 100
              required:
                - startDate
                - endDate
                - pageNumber
                - pageSize
              properties:
                startDate:
                  type: string
                  description: Мэдүүлэг татах эхлэх огноо
                  example: '2020-03-01'
                endDate:
                  type: string
                  description: 'Мэдүүлэг татах дуусан огноо '
                  example: '2024-03-30'
                pageNumber:
                  type: number
                  description: Хуудаслалтын дугаар
                  example: 1
                pageSize:
                  type: number
                  description: Хуудаслалтын хэмжээ
                  example: 100
components:
  securitySchemes:
    auth.yaml:
      type: http
      scheme: basic
    auth_copy.yaml:
      type: http
      scheme: bearer
servers: []
x-internal: false
