openapi: 3.1.0
x-stoplight:
  id: i6179fzdicgrc
info:
  title: Хялбар бүртгэлийн API холболт
  version: '2.0'
  description: "### Танилцуулга\r\n>Иргэний хувийн хэрэглээнд худалдан авсан бараа бүтээгдэхүүний худалдан авалт болон үйлчилгээний төлбөр төлсөн тухай бүр үйлдсэн төлбөрийн баримтын мэдээллийг автоматаар ибаримт системд бүртгэх үйлчилгээг хялбар бүртгэл гэнэ.\r\n\r\n![image (2).png](<../assets/images/Image (1).jpg>)\r\n\r\n\r\n### Өөрчлөлтийн түүх\r\n\r\n| № | Хувилбар | Огноо | Тайлбар | Хариуцагч |\r\n| -------- | ------- | ------- | ------- | ------- |\r\n| 1  | 1.0.0 | 08/09/2024 | Гарын авлага боловсруулав | Б.Мөнгөнчимэг   |\r\n"
  summary: ''
servers: []
paths:
  '/api/easy-register/api/info/consumer/{identity}':
    get:
      summary: Иргэний мэдээлэл регистр /иргэний бүртгэл-civilId/-ийн дугаараар лавлах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                properties:
                  regNo:
                    type: string
                    x-stoplight:
                      id: fmcwim5nw8hhd
                    description: Иргэний регистрийн дугаар
                  loginName:
                    type: string
                    x-stoplight:
                      id: 9wx8tk7ggo4wf
                    description: Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн код
                  givenName:
                    type: string
                    x-stoplight:
                      id: 649ogft223vxz
                    description: Хэрэглэгчийн нэр
                  familyName:
                    type: string
                    x-stoplight:
                      id: nirwrgraayufa
                    description: Хэрэглэгчийн овог
              examples:
                Example 1:
                  value:
                    regNo: ТЕ8****818
                    loginName: '11223344'
                    givenName: Очир
                    familyName: Даваа
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - code
                  - status
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: fy6x1hg3zrntt
                    description: Сервисийн хариу мессеж
                  code:
                    type: string
                    x-stoplight:
                      id: xpoip0hfeplxz
                    description: Сервисийн хариу код
                  status:
                    type: string
                    x-stoplight:
                      id: nch4exq4hnygf
                    description: Сервисийн хариу статус
              examples:
                Регистрийн дугаар бүртгэлгүй үед:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: '409'
      operationId: get-api-easy-register-api-info-consumer-regNo
      x-stoplight:
        id: tw03kv02n3xto
      description: '>Худалдан авагч иргэний мэдээлийг дараах зааврын дагуу лавлана.'
      security:
        - auth.yaml: []
    parameters:
      - schema:
          type: string
          example: АА01234567
        name: identity
        in: path
        description: Иргэний регистрийн дугаар болон иргэний бүртгэлийн дугаар/civilId/-ын нэг нь байна.
        required: true
    servers:
      - url: 'https://service.itc.gov.mn'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn'
        description: Хөгжүүлэлтийн орчин
  /api/easy-register/rest/v1/getProfile:
    servers:
      - url: 'https://service.itc.gov.mn/'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn/'
        description: Хөгжүүлэлтийн орчин
    post:
      summary: Иргэний мэдээллийг утасны дугаараар болон хэрэглэгчийн дугаараар лавлах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - code
                  - status
                  - loginName
                  - email
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: 2qspufxshxm4o
                    description: Сервисийн хариу
                  code:
                    type: string
                    x-stoplight:
                      id: sy9u9f3yr3huo
                    description: Сервисийн хариу
                  status:
                    type: number
                    x-stoplight:
                      id: dh3sb7aumd86o
                    description: Сервисийн хариу
                  loginName:
                    type: string
                    x-stoplight:
                      id: t24oewjrb4so5
                    description: "Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн\r\nкод."
                  email:
                    type: string
                    x-stoplight:
                      id: y90lauznv18g0
                    description: Хэрэглэгчийн цахим шуудан хаяг
              examples:
                Амжилттай:
                  value:
                    msg: Амжилттай.
                    code: success
                    status: 200
                    loginName: 11***475
                    email: munguu****@yahoo.com
                Хэрэглэгч олдоогүй:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: 409
                    loginName: ''
                    email: ''
                Давхар бүртгэлтэй хэрэглэгч:
                  value:
                    msg: Хэрэглэгчийн бүртгэл давхардсан байна.
                    code: userDuplicate
                    status: 409
                    loginName: ''
                    email: ''
                Насанд хүрээгүй хэрэглэгч:
                  value:
                    msg: Хэрэглэгч 14 наснаас доош байна.
                    code: userChild
                    status: 409
                    loginName: ''
                    email: ''
                Цахим шуудан хаяг бүртгэлгүй:
                  value:
                    msg: Имэйл олдсонгүй
                    code: emailNotFound
                    status: 409
                    loginName: ''
                    email: ''
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - code
                  - status
                  - loginName
                  - email
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: z37vz0dyfvg9z
                    description: Сервисийн хариу
                  code:
                    type: string
                    x-stoplight:
                      id: 5f5ys76h7fcx7
                    description: Сервисийн хариу
                  status:
                    type: number
                    x-stoplight:
                      id: kvj0axpn7kyyf
                    description: Сервисийн хариу
                  loginName:
                    type: string
                    x-stoplight:
                      id: 1lerxsw1vlv1r
                    description: "Ebarimt-н нэвртэх нэр буюу 8 оронтой хэрэглэгчийн\r\nкод"
                  email:
                    type: string
                    x-stoplight:
                      id: 04qxc2w77enxe
                    description: Хэрэглэгчийн цахим шуудан хаяг
              examples:
                Талбар хоосон:
                  value:
                    msg: Талбар хоосон байна.
                    code: emptyField
                    status: 400
                    loginName: ''
                    email: ''
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: post-api-easy-register-rest-v1-getProfile
      x-stoplight:
        id: rjhebiacnaqu3
      description: ">Худалдан авагч иргэний мэдээллийг утасны дугаараар болон хэрэглэгчийн дугаараар лавлах\r\n"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNum
                - customerNo
              properties:
                phoneNum:
                  type: string
                  x-stoplight:
                    id: 2u2zb3n11tgvk
                  description: Иргэний утасны дугаар /Хэрэглэгчийн дугаар талбарт өгөдөл оруулсан бол заавал биш/
                  example: '99999999'
                customerNo:
                  type: string
                  x-stoplight:
                    id: 6red199z4rq5p
                  description: Хэрэглэгчийн дугаарр./Иргэний утасны дугаар талбарт өгөдөл оруулсан бол заавал биш/
                  example: '10038071'
            examples:
              Утасны дугаараар лавлах:
                value:
                  phoneNum: 993***99
              Хэрэглэгчийн дугаараар лавлах:
                value:
                  customerNo: АА12345678
      security:
        - auth.yaml: []
  /api/easy-register/rest/v1/approveQr:
    get_copy:
      summary: Худалдан авагчийн баримтыг шууд баталгаажуулж бүртгүүлэх
      tags: []
      responses: {}
      operationId: get-api-easy-register-rest-v1-approveQr
      description: '>Энэхүү сервис нь тухайн иргэнийн ибаримтанд Баталгаажсан төлөвтэйгээр шууд бүртгэгдэх болно.'
    servers:
      - url: 'https://service.itc.gov.mn/'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn/'
        description: Хөгжүүлэлтийн орчин
    post:
      summary: Төлбөрийн баримт баталгаажуулах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - code
                  - status
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: l1abt23oun2j6
                    description: Сервисийн хариу
                  code:
                    type: string
                    x-stoplight:
                      id: h6xhl5rfwgaa8
                    description: Сервисийн хариу
                  status:
                    type: number
                    x-stoplight:
                      id: mway6srtvrkbg
                    description: Сервисийн хариу
              examples:
                Амжилттай:
                  value:
                    msg: Амжилттай.
                    code: SUCCESS
                    status: 200
                Хэрэглэгч олдсонгүй:
                  value:
                    msg: Хэрэглэгч олдсонгүй.
                    code: userNotFound
                    status: 409
                QR алдаатай:
                  value:
                    msg: qrData мэдээлэл алдаатай байна.
                    code: inValidQr
                    status: 500
                Мэдээлэл алдаатай:
                  value:
                    msg: Мэдээлэл алдаатай байна.
                    code: invalidData
                    status: 500
                Алдаатай:
                  value:
                    msg: Алдаа.
                    code: error
                    status: 500
                Баримтын төрөл буруу:
                  value:
                    msg: Байгууллага хооронд хийгдсэн гүйлгээ баталгаажуулах боломжгүй.
                    code: b2bNotAccepted
                    status: 500
                Сугалааны дугаар байхгүй:
                  value:
                    msg: Сугалаагүй баримт байна.
                    code: noLotteryQr
                    status: 409
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                  - code
                  - status
                properties:
                  msg:
                    type: string
                    x-stoplight:
                      id: ovaw7w1np0jxw
                    description: Сервисийн хариу
                  code:
                    type: string
                    x-stoplight:
                      id: m7budy5rl42o0
                    description: Сервисийн хариу
                  status:
                    type: number
                    x-stoplight:
                      id: nl1taz5sn0cze
                    description: Сервисийн хариу
              examples:
                Талбар хоосон:
                  value:
                    msg: Талбар хоосон байна.
                    code: emptyField
                    status: 400
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: post-api-easy-register-rest-v1-approveQr
      x-stoplight:
        id: 2ngrrpggc33bt
      description: '>Энэхүү сервис нь тухайн иргэнийн ибаримтанд Баталгаажсан төлөвтэйгээр шууд бүртгэгдэх болно.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - customerNo
                - qrData
              properties:
                customerNo:
                  type: string
                  x-stoplight:
                    id: qhrk2xcpo82a2
                  example: '10038071'
                  description: E-barimt-н нэвтрэх хэрэглэгчийн код. (8-9 оронтой тоо байх)
                qrData:
                  type: string
                  x-stoplight:
                    id: 1eptm1m18qydd
                  description: Төлбөрийн баримтын QR
            examples:
              Төлбөрийн баримтын баталгаажуулах:
                value:
                  customerNo: АА12345678
                  qrData: 138431709438294994***********42989187861711452070 67124287171260511392558330701380
      security:
        - auth.yaml: []
  '/api/easy-register/api/info/foreigner/{identity}':
    get:
      summary: Гадаад жуулчны мэдээллийг гадаад паспорт эсвэл F регистрийн дугаараар лавлах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - fNumber
                properties:
                  regNo:
                    type: string
                    x-stoplight:
                      id: ypcebt1278rue
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    x-stoplight:
                      id: ddnj7jhdilg0q
                    description: "Ebarimt-н нэвтрэх нэр буюу 8 оронтой хэрэглэгчийн код.\r\n"
                  givenName:
                    type: string
                    x-stoplight:
                      id: ykofwqkw9xohj
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    x-stoplight:
                      id: dzdx4c020uqla
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    x-stoplight:
                      id: ys7vulgs7jizk
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    x-stoplight:
                      id: 4awrcn9h5zbi3
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    x-stoplight:
                      id: jbeq7ccx6p3l7
                    description: Гадаад паспортын дугаар.
                  fNumber:
                    type: string
                    x-stoplight:
                      id: 8gzlgaa8eylbq
                    description: F регистрийн дугаар.
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    fNumber: '******'
      operationId: get-api-easy-register-api-info-foreigner
      x-stoplight:
        id: w2iwr4v1735yx
      description: '> Энэхүү сервис нь Монголын улсад аялаж байгаа гадаадын иргэний мэдээллийг f регистр болон гадаад паспортын дугаараар лавлахад ашиглагдана.'
      security:
        - auth.yaml: []
    parameters:
      - schema:
          type: string
          example: M709R8406
        name: identity
        in: path
        description: Гадаад пасспортын дугаар эсвэл Хил хамгаалах ерөнхий газраас олгосон F регистрийн дугаар /аль нэгийг нь оруулж лавлана.
        required: true
    servers:
      - url: 'https://service.itc.gov.mn/'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn'
        description: Хөгжүүлэлтийн орчин
  '/api/easy-register/api/info/foreigner/customerNo/{loginName}':
    get:
      summary: Гадаад жуулчны мэдээллийг E-barimt-н нэвтрэх нэрээр лавлах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - fNumber
                properties:
                  regNo:
                    type: string
                    x-stoplight:
                      id: aldhnx4cg0vyb
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    x-stoplight:
                      id: 7acnwy25ata07
                    description: Ebarimt-н нэвтрэх хэрэглэгчийн код.
                  givenName:
                    type: string
                    x-stoplight:
                      id: rsd9znzkbrmkj
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    x-stoplight:
                      id: hia3jlt2p0tpu
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    x-stoplight:
                      id: p9jmrs0lasvjo
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    x-stoplight:
                      id: rp0q634az3c7e
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    x-stoplight:
                      id: pqzl00mbrnjjh
                    description: Гадаад паспортын дугаар.
                  fNumber:
                    type: string
                    x-stoplight:
                      id: nzc0j3l2xwecy
                    description: F регистрийн дугаар.
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    fNumber: '*******'
      operationId: get-api-easy-register-api-info-foreigner-customerNo
      x-stoplight:
        id: 46fhh5l44b8n7
      description: '> Энэхүү сервис нь Монгол улсад аялаж байгаа гадаадын иргэний мэдээллийг ИБАРИМТ-ын нэвтрэх нэрээр лавлахад ашиглагдана.'
      security:
        - auth.yaml: []
    servers:
      - url: 'https://service.itc.gov.mn'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn'
        description: Хөгжүүлэлтийн орчин
    parameters:
      - schema:
          type: string
          example: '10038071'
        name: loginName
        in: path
        description: E-barimt-н нэвтрэх хэрэглэгчийн код. (8-9 оронтой тоо байх)
        required: true
  '/api/easy-register/api/info/foreigner/{passportNo}':
    parameters:
      - schema:
          type: string
          example: EK2658447
        name: passportNo
        in: path
        description: Гадаад пасспортын дугаар
        required: true
    servers:
      - url: 'https://service.itc.gov.mn'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn'
        description: Хөгжүүлэлтийн орчин
    post:
      summary: Гадаад жуулчны мэдээллийг E-barimt-н системд бүртгэх
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    message: You are already registered. Please check your oc********@itc.gov.mn
                    fNumber: ''
                required:
                  - regNo
                  - loginName
                  - givenName
                  - familyName
                  - refund
                  - country
                  - passportNo
                  - message
                  - fNumber
                properties:
                  regNo:
                    type: string
                    description: Гадаад иргэний регистрийн дугаар.
                  loginName:
                    type: string
                    description: Ebarimt-н нэвтрэх хэрэглэгчийн код.
                  givenName:
                    type: string
                    description: Хэрэглэгчийн нэр.
                  familyName:
                    type: string
                    description: Хэрэглэгчийн овог.
                  refund:
                    type: string
                    description: Буцаан олголт авах эсэх.
                  country:
                    type: string
                    description: Улсын нэр.
                  passportNo:
                    type: string
                    description: Гадаад паспортын дугаар.
                  message:
                    type: string
                    description: Сервисийн хариу
                  fNumber:
                    type: string
                    description: F регистрийн дугаар.
              examples:
                Амжилттай:
                  value:
                    regNo: '******'
                    loginName: '14154565'
                    givenName: O*********EG
                    familyName: G*******KH
                    refund: 'false'
                    country: KAZ
                    passportNo: N****8907
                    message: You are already registered. Please check your oc********@itc.gov.mn
                    fNumber: ''
      operationId: post-api-easy-register-api-info-foreigner-passportNo
      x-stoplight:
        id: 5vir10g82j2k0
      description: '>Гадаад жуулчны мэдээллийг Гадаад паспортын дугаар болон цахим шуудан хаягаар EBARIMT-н системд бүртгэх'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: hlg8cswhkvv15
                  description: Гадаад иргэний цахим шуудан хаяг
      security:
        - auth.yaml: []
  /api/easy-register/rest/v1/setReturnReceipt:
    post:
      summary: Хялбар бүртгэлээр бүртгэгдсэн төлбөрийн баримтын буцаалтыг баталгаажуулах сервис
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    msg: ' Амжилттай буцаасан.'
                    status: 200
                    code: null
                    data: null
                properties:
                  msg:
                    type: string
                    example: Амжилттай
                  status:
                    type: number
                    example: 200
                  code:
                    type: 'null'
                  data:
                    type: 'null'
              examples:
                Амжилтттай:
                  value:
                    msg: Амжилттай
                    status: 200
                    code: null
                    data: null
                ДДТД эсвэл сугалааны дугаар хоосон байна:
                  value:
                    msg: string
                    status: 0
                    code: null
                    data: null
                Баримтын мэдээлэл олдсонгүй:
                  value:
                    msg: Баримтын мэдээлэл олдсонгүй
                    status: 500
                    code: null
                    data: null
                Токены мэдээлэл алдаатай байна:
                  value:
                    msg: Токены мэдээлэл алдаатай байна
                    status: 500
                    code: null
                    data: null
                Өөр байгууллагын борлуулалтын баримт тул устгаж болохгүй:
                  value:
                    msg: Өөр байгууллагын борлуулалтын баримт тул устгаж болохгүй
                    status: 500
                    code: null
                    data: null
                Хэрэглэгч буцаах үйлдэл хийгээгүй баримт байна:
                  value:
                    msg: Хэрэглэгч буцаах үйлдэл хийгээгүй баримт байна
                    status: 500
                    code: null
                    data: null
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: post-api-easy-register-rest-v1-setReturnReceipt
      x-stoplight:
        id: 3fkgf3eaxg24i
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  posRno: 0000061********230518000112012889
              properties:
                posRno:
                  type: string
                  description: Төлбөрийн баримтын ДДТД /Сугалааны дугаар байхгүй бол ДДТД/
                  example: 0000061********230518000112012889
                lotteryNumber:
                  type: string
                  x-stoplight:
                    id: lhi0f7ritfbiu
                  description: Төлбөрийн баримтын сугалааны дугаар /ДДТД байхгүй бол сугалааны дугаар/
                  example: AA11111111
            examples:
              ДДТД дугаараар буцаалт хийх:
                value:
                  posRno: 0000061********230518000112012889
              Сугалааны дугаараар буцаалт хийх:
                value:
                  lotteryNumber: AA11111111
      description: '>Энэхүү сервис нь зөвхөн ПосАПИ системээс хэвлэсэн сугалаатай баримтын буцаалтыг баталгаажуулах зориулалттай ба буцаах үйлдэл хийж буй баримтыг иргэн талаас буцаасны дараа баталгаажуулах боломжтой болохыг анхаарна уу. Мөн “Багц баримт”-ын систем ашиглан илгээсэн толгой баримтыг буцаахад дэд баримт дагаж идэвхгүй болох ба дэд баримтыг дангаар нь буцаах боломжгүй. '
      parameters:
        - schema:
            type: string
            example: eaab09fdb83c4affc210b8fb96f9977db7978e8a
          in: header
          name: X-API-KEY
          required: true
          description: posapi@itc.gov.mn рүү хүсэлт илгээж авна
      security:
        - auth.yaml: []
    servers:
      - url: 'https://service.itc.gov.mn/'
        description: Бодит орчин
      - url: 'https://st-service.itc.gov.mn/'
        description: Туршилтын орчин
components:
  schemas: {}
  securitySchemes:
    auth.yaml:
      type: http
      scheme: bearer
x-internal: false
